import random
from unittest.main import main


class User:
    def __init__(self, email, password, confirmPassword):
        self.email = email
        self.password = password
        self.confirmPassword = confirmPassword
        
    users = []

    def createUser(email, password, confirmPassword):
        """
        This method creates a new user
        """
        newUser = User(email, password, confirmPassword)
        return newUser
        
    def saveUser(self):
        """
        This method saves user
        """
        User.users.append(self)
    
    def loginMessage(self):
        """
        This method diplays to user upon successful login
        """
        print("Login successful")
        
    @classmethod
    def displayUsers(display):
        return display.users
        
    
    @classmethod
    def deleteUsers(self):
        User.users.remove(self) 
        
        

class Credentials:
    def __init__(self, username, password):
        """
        This is a credentials constructor 
        """
        self.username = username
        self.password = password

    credentials = []
    
    def createNewCredentials(self, username, password):
        """
        This method creates new credentials
        """
        newCredentials = Credentials(username, password)
        return newCredentials
    
    def save_credentials(self, username, password):
        """
        This methods saves credentials
        """
        Credentials.credentials.append(self)
        
    def display_credentials(self,credentials):
        for credential in credentials:
            print(credential.username+" - "+credential.password)   
    
    def check_existance(self, email):
        """
        This is a method to check the existatnce of data
        """
        if Credentials.credentials:
            for credential in Credentials.credentials:
                if credential.email == email:
                    return True
            print("Details in the account provided doesn't exist")
        else:
            print("No saved data yet")
            
            
   
def main():
    while True:    
        print("*"*50)
        options = input("Hey there, what's  your name? ")
        login_options = input(f"How can I help you {options}. Kindly select option using the following short codes:\n cc - Create account.\n lg - Login\n")
        print("*"*50)
        if login_options == 'cc':
            print("Enter username / email address: \n")
            username = input()
            
            print("Choose password option: \n 1. Enter password\n2. Use autogenerated password\n")
            passwordoption = input()
            
            if passwordoption == "1":                
                print("Enter password: \n")
                password = input()
                
                print("Confirm password: \n")
                confirm_password = input()
                
                if password == confirm_password:
                    User.loginMessage()
                    break
                
                elif password!=confirm_password:
                    print("Passwords does not match")
                print("*"*50)
                    
            elif passwordoption == "2":
                password = random.randint(10000, 90000)
                # break
            
            else:
                print("Invalid input")
                
        createUser = User.createUser(username, password, 0)
        User.saveUser(createUser)
        print(f"Account created successfully with user {username}")
        print("*"*50)
        print("Welcome to password locker. Login")
        print("Enter your username: \n")
        login_username = input()
        print("\n")
        
        print("Enter your password: \n")
        login_password = input()
        
        if Credentials in Credentials.credentials:
            for credential in Credentials.credentials:
                if credential.username == login_username and credential.password == login_password:
                    prompt_selection = input("Kindly select the option you would like to do using number:\n 1. Store already existing account credentials.\n 2. Create new account credentials.\n 3. View account credentials and passwords. \n 4. Delete account details.")
                else:
                    print("Incorrect username or password")
                    break
                    
            if prompt_selection == "1":
                for user in User.users:
                    Credentials.save_credentials(username, password)
                print(f"Your credentials {user} have been save successfully.")
            
            elif prompt_selection == "2":
                print = ("Enter your username: \n")
                newAccount = input()
                
                print=("Enter your password: \n")
                newPassword = input()
                Credentials.createNewCredentials(newAccount, newPassword)
                Credentials.save_credentials(newAccount, newPassword)
            
            elif prompt_selection == "3":
                Credentials.display_credentials(Credentials.credentials)
            
            elif prompt_selection == "4":
                pass
            
            else:
                print("Invalid selection")
main()
